### ISSUE TITLE
Flag hit box too small

### ISSUE THREAD

**Issue by ShadowStall** [LuisChecaUniversity/The-A-Team#5] opened 2015-04-14 16:05 UTC
When moving the player over the enemy flag you cannot pick up the flag unless you are directly over it, the issue is that the player looks as if it can pickup the flag however it does not pick it up
Steps to recreate it :
-1. start game 
-2. choose single player or dual 
-3. move player towards flag 
-4. can move behind flag without picking it up by colliding with the wall
Frequency of occurrence: 100%

![pickup box](https://cloud.githubusercontent.com/assets/9462284/7141301/7ca776ce-e2c8-11e4-962f-c5b7699255f1.png)

**Comment by ghost** [comment] 2015-04-14 16:15
duplicate of #4 :)

**Closed as completed** 2015-04-15 12:28 UTC
Labels: duplicate
